name: App Debug APK

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: ./.github/actions/load-build-versions
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle
      - uses: actions/setup-go@v7
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: 'libcore/go.sum'
      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: ${{ env.ANDROID_NDK_VERSION }}
      - uses: actions/cache@v6
        with:
          path: composeApp/libs
          key: libcore-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('libcore/go.sum', 'libcore/build.sh', 'husi.properties') }}
          restore-keys: libcore-${{ runner.os }}-${{ runner.arch }}-
      - name: Prepare assets
        run: make assets
      - name: Build Android libcore
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: make libcore_android
      - name: Generate about libraries metadata
        run: make aboutlibraries_go aboutlibraries_android
      - name: Build Android app (debug)
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: make apk_debug
      - uses: actions/upload-artifact@v7
        with:
          name: app-debug
          path: androidApp/build/outputs/apk/**/*.apk
          if-no-files-found: error
